# Site Data
title: Michelleby's Code Sandbox
email: michelleby@outlook.com
description: >-
  A place to store and to share solutions to common algorith problems.
baseurl: "/" 
url: "https://code.michelleby.com" 
github_username: Michelleeby
theme: minima
plugins:
  - jekyll-feed
include: [".htaccess", "_code_files"]
defaults:
  -
    scope:
      path: ""
      type: "prompts"
    values:
      layout: "prompt"
      permalink: prompts/:prompt/
  - 
    scope:
      path: "_code_files"
    values:
      code_file: true
logo: "assets/img/logo.png"
icon_dir: "assets/img/icons/"
collections:
  about:
    order: 
      - googlesheets.md
      - jekyll.md
      - githubpages.md
      - www.md
# Plugin Data
jekyll_google_api_generator:
  api_key: "AIzaSyArB_XqvEUMwL4F1yqhYVbfn367L6Kou10"
  spreadsheet_id: "12_0Hc7D6VliVqrQkOMZ4MP-cu2j4xwq1q26b8ZBYoUU"
  sheets_to_fetch:
    - title: "prompts"
      range: "A:F"
    - title: "solutions"
      range: "A:C"
    - title: "files"
      range: "A:C"
  output_dir: "_data"
